services:
  nijahomzs-postgres:
    image: postgres:16-alpine
    container_name: nijahomzs_postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: ${APP_POSTGRES_DATABASE:-nijahomzs}
      POSTGRES_USER: ${APP_POSTGRES_USERNAME:-nijahomzs}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD:-change-me-long-random-password}
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "max_connections=40"
    volumes:
      - nijahomzs_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_POSTGRES_USERNAME:-nijahomzs} -d ${APP_POSTGRES_DATABASE:-nijahomzs}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nijahomzs_postgres:

